
development:
  adapter: postgresql
  encoding: unicode
  database: abcrowd_composers_development
  pool: 5
  username: scottsMac
  host: localhost
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: abcrowd_composers_test
  pool: 5
  username: scottsMac
  host: localhost
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: abcrowd_composers_production
  pool: 5
  username: abcrowd_composers
  password:
